include: package:flutter_lints/flutter.yaml

linter:

  rules:

analyzer:
  errors:
    use_key_in_widget_constructors: ignore
    unnecessary_cast: ignore
    prefer_const_constructors_in_immutables: ignore
    prefer_const_constructors: ignore
    avoid_unnecessary_containers: ignore
    sort_child_properties_last: ignore
    avoid_function_literals_in_foreach_calls: ignore
    prefer_const_literals_to_create_immutables: ignore